version: '3.4'

services:
  inj-efficiency-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/inj-efficiency-epics-ioc:${IMAGE_VERSION}
    container_name: inj-efficiency-epics-ioc-${INJ_EFFICIENCY_INSTANCE}
    command: "\
        -t ${INJ_EFFICIENCY_TELNET_PORT} \
        -P ${INJ_EFFICIENCY_AREA_PREFIX} \
        -R ${INJ_EFFICIENCY_DEVICE_PREFIX} \
        -f ${INJ_EFFICIENCY_ICT1} \
        -s ${INJ_EFFICIENCY_ICT2}"
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/inj-efficiency-epics-ioc/iocBoot/iocInjEfficiency/autosave
    network_mode: "host"
