version: '3.4'

services:
  dmm7510-epics-ioc-1:
    image: dockerregistry.lnls-sirius.com.br/dmm7510-epics-ioc:${DMM7510_1_IMAGE_VERSION}
    container_name: dmm7510-epics-ioc-${DMM7510_1_INSTANCE}
    command: "\
        -t \"${DMM7510_1_TELNET_PORT}\" \
        -i \"${DMM7510_1_IP}\" \
        -p \"${DMM7510_1_PORT}\" \
        -d \"${DMM7510_1_INSTANCE}\" \
        -P \"${DMM7510_1_AREA_PREFIX}\" \
        -R \"${DMM7510_1_DEVICE_PREFIX}\" \
        "
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/dmm7510-epics-ioc/iocBoot/iocdmm7510/autosave
    network_mode: "host"

  dmm7510-epics-ioc-2:
    image: dockerregistry.lnls-sirius.com.br/dmm7510-epics-ioc:${DMM7510_2_IMAGE_VERSION}
    container_name: dmm7510-epics-ioc-${DMM7510_2_INSTANCE}
    command: "\
        -t \"${DMM7510_2_TELNET_PORT}\" \
        -i \"${DMM7510_2_IP}\" \
        -p \"${DMM7510_2_PORT}\" \
        -d \"${DMM7510_2_INSTANCE}\" \
        -P \"${DMM7510_2_AREA_PREFIX}\" \
        -R \"${DMM7510_2_DEVICE_PREFIX}\" \
        "
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/dmm7510-epics-ioc/iocBoot/iocdmm7510/autosave
    network_mode: "host"

  inj-efficiency-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/inj-efficiency-epics-ioc:${INJEFF_IMAGE_VERSION}
    container_name: inj-efficiency-epics-ioc-${INJEFF_INSTANCE}
    command: "\
        -t \"${INJEFF_TELNET_PORT}\" \
        -P \"${INJEFF_AREA_PREFIX}\" \
        -R \"${INJEFF_DEVICE_PREFIX}\" \
        -f \"${INJEFF_ICT1}\" \
        -s \"${INJEFF_ICT2}\" \
        "
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/inj-efficiency-epics-ioc/iocBoot/iocInjEfficiency/autosave
    network_mode: "host"
    depends_on:
      - dmm7510-epics-ioc-1
      - dmm7510-epics-ioc-2
