version: '3.4'

services:
  dmm7510-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/dmm7510-epics-ioc:${IMAGE_VERSION}
    container_name: dmm7510-epics-ioc-${DMM7510_INSTANCE}
    command: "\
        -t ${DMM7510_TELNET_PORT} \
        -i ${DMM7510_IP} \
        -p ${DMM7510_PORT} \
        -d ${DMM7510_INSTANCE} \
        -P ${DMM7510_AREA_PREFIX} \
        -R ${DMM7510_DEVICE_PREFIX}"
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/dmm7510-epics-ioc/iocBoot/iocdmm7510/autosave
    network_mode: "host"
