version: '3.4'

services:
  galil-dmc30017-in-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/lnlsdig/galil-dmc30017-epics-ioc:${DMC30017_IN_IMAGE_VERSION}
    container_name: galil-dmc30017-epics-ioc-${DMC30017_IN_INSTANCE}
    command: "\
        -t \"${DMC30017_IN_TELNET_PORT}\" \
        -i \"${DMC30017_IN_DEVICE_IP}\" \
        -p \"${DMC30017_IN_DEVICE_PORT}\" \
        -P \"${DMC30017_IN_AREA_PREFIX}\" \
        -R \"${DMC30017_IN_DEVICE_PREFIX}\" \
        -s \"${DMC30017_IN_VELO}\" \
        -x \"${DMC30017_IN_VMAX}\" \
        -a \"${DMC30017_IN_ACCL}\" \
        -d \"${DMC30017_IN_BDST}\" \
        -v \"${DMC30017_IN_BVEL}\" \
        -c \"${DMC30017_IN_BACC}\" \
        -r \"${DMC30017_IN_MRES}\" \
        -T \"${DMC30017_IN_SREV}\" \
        -e \"${DMC30017_IN_ERES}\" \
        -h \"${DMC30017_IN_DHLM}\" \
        -l \"${DMC30017_IN_DLLM}\" \
        -o \"${DMC30017_IN_OFF}\" \
        -u \"${DMC30017_IN_UEIP}\" \
        -y \"${DMC30017_IN_RTRY}\" \
        -n \"${DMC30017_IN_NTM}\" \
        -m \"${DMC30017_IN_MTRTYPE}\" \
        -k \"${DMC30017_IN_MTRON}\" \
        -g \"${DMC30017_IN_EGU}\" \
        -w \"${DMC30017_IN_DEFAULT_HOMETYPE}\" \
        -z \"${DMC30017_IN_DEFAULT_LIMITTYPE}\" \
        -G \"${DMC30017_IN_AMP_GAIN}\" \
        -D \"${DMC30017_IN_DIR}\" \
        -E \"${DMC30017_IN_ENC_TYPE}\" \
        -O \"${DMC30017_IN_BISS_POOL}\" \
        -C \"${DMC30017_IN_BISS_CLKDIV}\" \
        -A \"${DMC30017_IN_BISS_DATA1}\" \
        -B \"${DMC30017_IN_BISS_DATA2}\" \
        -Z \"${DMC30017_IN_BISS_ZEROPAD}\" \
        -I \"${DMC30017_IN_BISS_INPUT}\" \
        -L \"${DMC30017_IN_BISS_LEVEL}\" "
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/galil-dmc30017-epics-ioc/iocBoot/iocGalilDmc30017/autosave
    network_mode: "host"

  galil-dmc30017-out-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/lnlsdig/galil-dmc30017-epics-ioc:${DMC30017_OUT_IMAGE_VERSION}
    container_name: galil-dmc30017-epics-ioc-${DMC30017_OUT_INSTANCE}
    command: "\
        -t \"${DMC30017_OUT_TELNET_PORT}\" \
        -i \"${DMC30017_OUT_DEVICE_IP}\" \
        -p \"${DMC30017_OUT_DEVICE_PORT}\" \
        -P \"${DMC30017_OUT_AREA_PREFIX}\" \
        -R \"${DMC30017_OUT_DEVICE_PREFIX}\" \
        -s \"${DMC30017_OUT_VELO}\" \
        -x \"${DMC30017_OUT_VMAX}\" \
        -a \"${DMC30017_OUT_ACCL}\" \
        -d \"${DMC30017_OUT_BDST}\" \
        -v \"${DMC30017_OUT_BVEL}\" \
        -c \"${DMC30017_OUT_BACC}\" \
        -r \"${DMC30017_OUT_MRES}\" \
        -T \"${DMC30017_OUT_SREV}\" \
        -e \"${DMC30017_OUT_ERES}\" \
        -h \"${DMC30017_OUT_DHLM}\" \
        -l \"${DMC30017_OUT_DLLM}\" \
        -o \"${DMC30017_OUT_OFF}\" \
        -u \"${DMC30017_OUT_UEIP}\" \
        -y \"${DMC30017_OUT_RTRY}\" \
        -n \"${DMC30017_OUT_NTM}\" \
        -m \"${DMC30017_OUT_MTRTYPE}\" \
        -k \"${DMC30017_OUT_MTRON}\" \
        -g \"${DMC30017_OUT_EGU}\" \
        -w \"${DMC30017_OUT_DEFAULT_HOMETYPE}\" \
        -z \"${DMC30017_OUT_DEFAULT_LIMITTYPE}\" \
        -G \"${DMC30017_OUT_AMP_GAIN}\" \
        -D \"${DMC30017_OUT_DIR}\" \
        -E \"${DMC30017_OUT_ENC_TYPE}\" \
        -O \"${DMC30017_OUT_BISS_POOL}\" \
        -C \"${DMC30017_OUT_BISS_CLKDIV}\" \
        -A \"${DMC30017_OUT_BISS_DATA1}\" \
        -B \"${DMC30017_OUT_BISS_DATA2}\" \
        -Z \"${DMC30017_OUT_BISS_ZEROPAD}\" \
        -I \"${DMC30017_OUT_BISS_INPUT}\" \
        -L \"${DMC30017_OUT_BISS_LEVEL}\" "
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/galil-dmc30017-epics-ioc/iocBoot/iocGalilDmc30017/autosave
    network_mode: "host"

  diff-ctrl-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/lnlsdig/diff-ctrl-epics-ioc:${SCRAPER_IMAGE_VERSION}
    container_name: diff-ctrl-epics-ioc-${SCRAPER_INSTANCE}
    command: "\
        -t \"${SCRAPER_TELNET_PORT}\" \
        -p \"${SCRAPER_OUT_CTRL_PREFIX}\" \
        -n \"${SCRAPER_IN_CTRL_PREFIX}\" \
        -P \"${SCRAPER_AREA_PREFIX}\" \
        -R \"${SCRAPER_DEVICE_PREFIX}\" \
        -d \"${SCRAPER_DEVICE_TYPE}\" \
        -l \"${SCRAPER_LOW_LIM}\" \
        -h \"${SCRAPER_HIGH_LIM}\" \
        -a \"${SCRAPER_NEG_LIM}\" \
        -r \"${SCRAPER_POS_LIM}\" \
        -g \"${SCRAPER_EGU}\" "
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/diff-ctrl-epics-ioc/iocBoot/iocDiffCtrl/autosave
    network_mode: "host"
    depends_on:
      - galil-dmc30017-in-epics-ioc
      - galil-dmc30017-out-epics-ioc

