version: '3.4'

services:
  rsfsx-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/lnlsdig/rsfsx-epics-ioc:${TUNE_PROC_IMAGE_VERSION}
    container_name: rsfsx-epics-ioc-${TUNE_PROC_INSTANCE}
    command: "\
        -t ${TUNE_PROC_TELNET_PORT} \
        -i ${TUNE_PROC_IP} \
        -P ${TUNE_PROC_AREA_PREFIX} \
        -R ${TUNE_PROC_DEVICE_PREFIX} \
        -d ${TUNE_PROC_DEVICE}"
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/rsfsx-epics-ioc/iocBoot/iocrsfsx/autosave
    network_mode: "host"

  valon5009-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/lnlsdig/valon5009-epics-ioc:${CARRIER_GEN_IMAGE_VERSION}
    container_name: valon5009-epics-ioc-${CARRIER_GEN_INSTANCE}
    command: "\
        -t ${CARRIER_GEN_TELNET_PORT} \
        -i ${CARRIER_GEN_IP}
        -p ${CARRIER_GEN_PORT} \
        -P ${CARRIER_GEN_AREA_PREFIX} \
        -R ${CARRIER_GEN_DEVICE_PREFIX} \
        -d ${CARRIER_GEN_DEVICE}"
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/valon5009-epics-ioc/iocBoot/iocValon5009/autosave
    network_mode: "host"

  agilent33521a-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/lnlsdig/agilent33521a-epics-ioc:${NOISE_GEN_IMAGE_VERSION}
    container_name: agilent33521a-epics-ioc-${NOISE_GEN_INSTANCE}
    command: "\
        -t ${NOISE_GEN_TELNET_PORT} \
        -i ${NOISE_GEN_IP} \
        -p ${NOISE_GEN_PORT} \
        -P ${NOISE_GEN_AREA_PREFIX} \
        -R ${NOISE_GEN_DEVICE_PREFIX}"
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/agilent33521a-epics-ioc/iocBoot/iocagilent33521a/autosave
    network_mode: "host"

  ar-amp-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/lnlsdig/ar-amp-epics-ioc:${ARAMP_IMAGE_VERSION}
    container_name: ar-amp-epics-ioc-${ARAMP_INSTANCE}
    command: "\
        -t ${ARAMP_TELNET_PORT} \
        -i ${ARAMP_IP} \
        -p ${ARAMP_PORT} \
        -P ${ARAMP_AREA_PREFIX} \
        -R ${ARAMP_DEVICE_PREFIX} \
        -d ${ARAMP_DEVICE}"
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/ar-amp-epics-ioc/iocBoot/iocARAmp/autosave
    network_mode: "host"

  tune-epics-ioc:
    image: dockerregistry.lnls-sirius.com.br/lnlsdig/tune-epics-ioc:${TUNE_IMAGE_VERSION}
    container_name: tune-epics-ioc-${TUNE_INSTANCE}
    command: "\
        -t ${TUNE_TELNET_PORT} \
        -n ${TUNE_NOISE_GEN} \
        -c ${TUNE_CARRIER_GEN} \
        -s ${TUNE_PROC} \
        -a ${TUNE_ARAMP} \
        -P ${TUNE_AREA_PREFIX} \
        -R ${TUNE_DEVICE_PREFIX} \
        -d ${TUNE_DEVICE}"
    volumes:
      - type: bind
        source: /media/autosave
        target: /opt/epics/startup/ioc/tune-epics-ioc/iocBoot/iocTune/autosave
    network_mode: "host"
    depends_on:
      - rsfsx-epics-ioc
      - valon5009-epics-ioc
      - agilent33521a-epics-ioc
      - ar-amp-epics-ioc
